import { listWorkOrders } from "./api.js";
const host=()=>document.getElementById("work-orders-workspace");
const names=["Январь","Февраль","Март","Апрель","Май","Июнь","Июль","Август","Сентябрь","Октябрь","Ноябрь","Декабрь"];
const escapeHtml=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const money=v=>new Intl.NumberFormat("ru-RU",{maximumFractionDigits:2}).format(Number(v)||0)+" ₽";
let year=new Date().getFullYear(),month=new Date().getMonth()+1,active=false,requestId=0,rows=[],total=0;
function render(){const el=host();if(!el)return;el.innerHTML=`<section class="orders-shell"><header class="orders-header"><h1>Заказ-наряды</h1><span class="orders-snapshot">Данные из базы</span></header><div id="orders-content"></div><div class="orders-bottom"><div class="orders-period"><select id="orders-year" aria-label="Год">${Array.from({length:5},(_,i)=>year-2+i).map(y=>`<option value="${y}" ${y===year?"selected":""}>${y}</option>`).join("")}</select><select id="orders-quarter" aria-label="Квартал">${[1,2,3,4].map(q=>`<option value="${q}" ${q===Math.ceil(month/3)?"selected":""}>${q} квартал</option>`).join("")}</select><select id="orders-month" aria-label="Месяц">${names.map((n,i)=>`<option value="${i+1}" ${i+1===month?"selected":""}>${n}</option>`).join("")}</select></div><nav class="orders-navigation" aria-label="Разделы заказ-нарядов"></nav></div></section>`;el.querySelector("#orders-year").onchange=e=>{year=Number(e.target.value);void load()};el.querySelector("#orders-quarter").onchange=e=>{month=(Number(e.target.value)-1)*3+1;render();void load()};el.querySelector("#orders-month").onchange=e=>{month=Number(e.target.value);render();void load()};}
async function load(){const token=++requestId;const content=host()?.querySelector("#orders-content");if(!content)return;content.textContent="Загрузка…";try{const result=await listWorkOrders({year,month});if(!active||token!==requestId)return;rows=Array.isArray(result.rows)?result.rows:[];total=Number(result.total_count??rows.length);content.innerHTML=`<div class="orders-count">${total} заказ-нарядов</div>${rows.map(r=>`<article class="orders-card"><div class="orders-card-line"><strong>ЗН №${escapeHtml(r.number)}</strong><strong>${money(r.total_final_amount)}</strong></div><div class="orders-meta">${escapeHtml(r.document_date||"")} · ${escapeHtml(r.status||"")}</div></article>`).join("")||'<p class="orders-empty">Нет заказ-нарядов за выбранный месяц</p>'}`; }catch(error){console.error("work_orders_list_failed",error);if(active&&token===requestId)content.innerHTML='<p class="orders-empty">Не удалось загрузить заказ-наряды</p><button id="orders-retry">Повторить</button>',content.querySelector("#orders-retry").onclick=()=>void load();}}
export const workOrdersPage={code:"work_orders",name:"Заказ-наряды",async activate(){active=true;host().hidden=false;render();await load()},deactivate(){active=false;requestId++;host().hidden=true}};
